### ISSUE TITLE
Output in log to verify this is working with docker-immich?

### ISSUE THREAD

**Issue by travisboss** [imagegenius/docker-immich-cuda-node#11]
Is there anything I should be seeing in the logs of this container if any sort of GPU work is being done?

**Comment by hydazz** [comment]
the container wont start unless it can find a GPU, it will spit out a bunch of errors and boot loop, you can also check `nvidia-smi`

**Comment by travisboss** [comment]
@hydazz I use nvidia-smi container, so using the way you suggest will not work, I believe it is working fine it is not spitting out a bunch of errors, I thought it might have some logs if it is transcoding is all.

**Comment by martabal** [comment]
Yes, like the official machine-learning or the one in the AIO image, it should print in your logs when a new image is being processed. This machine-learning is "just" an immich machine-learning with all dependencies required to run the machine-learning jobs with a GPU.
